name:                ntfd
version:             0.1.0
github:              "kamek-pf/ntfd"
license:             GPL-3
author:              "Bertrand Bousquet"
maintainer:          "b.kamek@gmail.com"
copyright:           "2020 Bertrand Bousquet"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kamek-pf/ntfd#readme>

dependencies:
- base >= 4.7 && < 5
- text
- containers
- bytestring
- vector
- time
- aeson
- tomland
- async
- http-conduit
- microstache
- parsec
- dbus
- libmpd
- directory
- filepath

default-extensions:
- OverloadedStrings
- RecordWildCards
- NamedFieldPuns
- ScopedTypeVariables

ghc-options:
- -Wall
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Wcompat
- -Widentities
- -Wredundant-constraints
- -Wmissing-export-lists
- -Wpartial-fields

library:
  source-dirs: src

executables:
  ntfd:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - ntfd
    # This block messes up stack commands, we only need it
    # so Docker can build static binaries.
    # It's used in by Docker builds, don't remove it.
    ## ghc-options:
    ## - -O2
    ## - -fPIC
    ## - -fllvm
    ## ld-options: -static -Wl,--unresolved-symbols=ignore-all

tests:
  ntfd-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wno-incomplete-uni-patterns
    - -Wno-missing-export-lists
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ntfd
    - hspec
