name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v17
      
      - uses: cachix/cachix-action@v10
        with:
          name: lfdominguez
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
          extraPullNames: 'nix-community,https://cache.iog.io'
      
      - run: nix build 
